auth_enabled: false

server:
  http_listen_port: 3100

ingester:
  wal:
    dir: /tmp/loki/wal
  lifecycler:
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1

storage_config:
  tsdb_shipper:
    active_index_directory: /data/tsdb-index
    cache_location: /data/tsdb-cache
  filesystem:
    directory: /data/chunks

limits_config:
  # reject_old_samples: true
  reject_old_samples_max_age: 168h
  retention_period: 720h  # 30 days
  # allow_structured_metadata defaults to true

# query_scheduler:
#   max_outstanding_requests_per_tenant: 32768

querier:
  max_concurrent: 2

schema_config:
  configs:
    - from: "2023-01-05"
      index:
        period: 24h
        prefix: index_
      object_store: filesystem
      schema: v13
      store: tsdb

compactor:
  working_directory: /data/tsdb-compactor
  retention_enabled: true
  delete_request_store: filesystem
